@ECHO OFF
SETLOCAL ENABLEEXTENSIONS

SET /A errno=0
SET /A ERROR_HELP_SCREEN=1
SET /A ERROR_COMMAND_NOT_FOUND=2
SET /A ERROR_COMMAND_FAILED=4

sth.exe
IF %ERRORLEVEL% NEQ 0 SET /A errno^|=%ERROR_COMMAND_NOT_FOUND%

sth.exe
IF %ERRORLEVEL% NEQ 0
(
	SET /A errno^|=%ERROR_COMMAND_FAILED%
)

EXIT /B %errno%